events {}
http {
  upstream ml {
    server host.docker.internal:8001;   # blue
    # server host.docker.internal:8002; # green
  }
  server {
    listen 80;
    location / { proxy_pass http://ml; }
  }
}
